//! The `docs/reference/cli.md` renderer — a deterministic projection of the CLI
//! surface from the [`crate::help`] SSOT.
//!
//! Every fact — a command name, its synopsis, its argument description, its
//! flags, and the section it belongs to — is read from [`crate::help`]'s
//! projections ([`crate::help::all_command_specs`],
//! [`crate::help::all_section_specs`], [`crate::help::all_group_specs`]), the
//! same tables the dispatcher and the terminal `--help` screen read. The
//! reference therefore cannot describe a command the CLI does not accept, nor
//! miss a flag the CLI does: adding a command or a flag to `help::COMMANDS`
//! moves this output, and the drift gate (`gen-cli-docs` +
//! `tools/scripts/generated-unchanged.sh`) reddens the build until the
//! committed `cli.md` is regenerated.
//!
//! The output is byte-deterministic: sections, groups, and commands appear in
//! registry order, so the same tables always produce byte-identical Markdown.

use std::fmt::Write as _;

use crate::help::{self, CommandSpec, GroupSpec, SectionSpec};

/// The sentinel every generated reference carries so a hand edit is obvious and
/// the drift gate's failure message can point at the generator.
pub const GENERATED_SENTINEL: &str = "Generated by gen-cli-docs. Do not edit by hand.";

/// Render `docs/reference/cli.md` from the CLI help SSOT.
///
/// Reads the live [`crate::help`] projections, so the argument is the SSOT
/// itself rather than a passed-in copy — there is only one CLI surface.
#[must_use]
pub fn render_cli_docs() -> String {
    render_from(
        &help::all_command_specs(),
        &help::all_section_specs(),
        &help::all_group_specs(),
    )
}

/// Render the reference from explicit specs. Split from [`render_cli_docs`] so a
/// test can drive it with the live tables while the layout stays one function.
#[must_use]
pub fn render_from(
    commands: &[CommandSpec],
    sections: &[SectionSpec],
    groups: &[GroupSpec],
) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "<!-- {GENERATED_SENTINEL} -->\n");
    out.push_str("# CLI reference\n\n");
    out.push_str(
        "Every `ipe` command, its synopsis, arguments, and flags — the surface \
         the dispatcher accepts and the terminal `ipe --help` screen renders, \
         from a single source (`help::COMMANDS`). Commands are grouped by the \
         top-level help sections; a group node (e.g. `dev`) lists its member \
         verbs.\n\n",
    );

    render_toc(&mut out, sections, groups);
    render_sections(&mut out, commands, sections, groups);
    render_groups_appendix(&mut out, commands, groups);

    out
}

/// The table of contents: one anchored bullet per section.
fn render_toc(out: &mut String, sections: &[SectionSpec], groups: &[GroupSpec]) {
    out.push_str("## Sections\n\n");
    for section in sections {
        let anchor = anchor(section.title);
        let _ = writeln!(out, "- [{title}](#{anchor})", title = section.title);
    }
    if !groups.is_empty() {
        let _ = writeln!(out, "- [Command groups](#command-groups)");
    }
    out.push('\n');
}

/// Per-section command bodies, in registry order.
fn render_sections(
    out: &mut String,
    commands: &[CommandSpec],
    sections: &[SectionSpec],
    groups: &[GroupSpec],
) {
    for section in sections {
        let _ = writeln!(out, "## {}\n", section.title);
        for &name in &section.commands {
            if let Some(cmd) = find_command(commands, name) {
                render_command(out, cmd);
            } else if let Some(group) = find_group(groups, name) {
                render_group(out, group);
            }
            // A name that is neither a command nor a group is impossible — the
            // help SSOT's own tests already assert every section entry resolves
            // — so no fallback branch can silently swallow one.
        }
    }
}

/// A group node inside a section: its name, summary, and a link to each member
/// verb (whose full body lives in the command-groups appendix).
fn render_group(out: &mut String, group: &GroupSpec) {
    let _ = writeln!(out, "### `ipe {}`\n", group.name);
    let _ = writeln!(out, "{}\n", group.summary);
    out.push_str(crate::text::verbs_label());
    out.push_str("\n\n");
    for &verb in &group.members {
        let _ = writeln!(out, "- `ipe {verb}`");
    }
    out.push('\n');
}

/// The command-groups appendix (only when there is at least one group): the full
/// body of each grouped verb, so `ipe dev build` is documented once under its
/// group rather than as its own top-level line.
fn render_groups_appendix(out: &mut String, commands: &[CommandSpec], groups: &[GroupSpec]) {
    if groups.is_empty() {
        return;
    }
    out.push_str("## Command groups\n\n");
    out.push_str(
        "A group is invoked as `ipe <group> <verb>`; the group fixes the \
         verb's build posture, and each verb is dispatched and described from \
         the one registry.\n\n",
    );
    for group in groups {
        let _ = writeln!(out, "### `ipe {}` verbs\n", group.name);
        for &verb in &group.members {
            if let Some(cmd) = find_command(commands, verb) {
                render_command(out, cmd);
            }
        }
    }
}

/// One command's body: heading, summary, synopsis code block, arguments, flags.
fn render_command(out: &mut String, cmd: &CommandSpec) {
    let _ = writeln!(out, "### `ipe {}`\n", cmd.name);
    let _ = writeln!(out, "{}\n", cmd.summary);

    let _ = write!(out, "```\nipe {}", cmd.name);
    if !cmd.args.is_empty() {
        let _ = write!(out, " {}", cmd.args);
    }
    out.push_str("\n```\n\n");

    if !cmd.args_desc.is_empty() {
        let _ = writeln!(out, "**Arguments:** {}\n", cmd.args_desc);
    }

    if !cmd.output_desc.is_empty() {
        let _ = writeln!(out, "**Output:** {}\n", cmd.output_desc);
    }

    if !cmd.options.is_empty() {
        out.push_str("**Flags:**\n\n");
        for opt in &cmd.options {
            let _ = writeln!(out, "- `{}` — {}", opt.flag, opt.desc);
        }
        out.push('\n');
    }
}

/// Find a command spec by name.
fn find_command<'a>(commands: &'a [CommandSpec], name: &str) -> Option<&'a CommandSpec> {
    commands.iter().find(|c| c.name == name)
}

/// Find a group spec by name.
fn find_group<'a>(groups: &'a [GroupSpec], name: &str) -> Option<&'a GroupSpec> {
    groups.iter().find(|g| g.name == name)
}

/// Convert a section title to a GitHub-Markdown anchor slug (lowercased,
/// non-alphanumerics dropped, spaces and dashes → `-`). Mirrors the env-doc
/// generator's slug rule so the two references anchor the same way.
fn anchor(title: &str) -> String {
    title
        .chars()
        .filter_map(|c| {
            if c.is_alphanumeric() {
                Some(c.to_ascii_lowercase())
            } else if c == ' ' || c == '-' {
                Some('-')
            } else {
                None
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_byte_idempotent() {
        let first = render_cli_docs();
        let second = render_cli_docs();
        assert_eq!(first, second, "two renders must be byte-identical");
    }

    #[test]
    fn render_carries_the_generated_sentinel() {
        let out = render_cli_docs();
        assert!(
            out.contains(GENERATED_SENTINEL),
            "output must carry the generated-file sentinel"
        );
    }

    /// Every advertised (non-hidden) command must appear in the rendered
    /// reference — the reference documents the full surface it claims to.
    #[test]
    fn every_advertised_command_is_documented() {
        let out = render_cli_docs();
        for cmd in help::all_command_specs() {
            if cmd.hidden {
                continue;
            }
            assert!(
                out.contains(&format!("### `ipe {}`", cmd.name)),
                "command `{}` is advertised but not documented in cli.md",
                cmd.name
            );
        }
    }

    /// Every flag of every command must be rendered — an added flag that is not
    /// documented moves this output, which the drift gate then catches.
    #[test]
    fn every_flag_is_documented() {
        let out = render_cli_docs();
        for cmd in help::all_command_specs() {
            for opt in &cmd.options {
                assert!(
                    out.contains(opt.flag),
                    "flag `{}` of command `{}` is not documented in cli.md",
                    opt.flag,
                    cmd.name
                );
            }
        }
    }
}
