// Generated by Ipê (Rust target)
#![allow(unused, non_snake_case)]

#[cfg(feature = "alloc_dlmalloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: dlmalloc::GlobalDlmalloc = dlmalloc::GlobalDlmalloc;

#[cfg(feature = "alloc_mimalloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub use ipe_runtime::*;

use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fmt;
use std::future::Future;
use std::future::ready;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll, Wake, Waker};

// Basic types
type IpeInt = i64;
type IpeFloat = f64;
type IpeBool = bool;
type IpeString = String;
type Value = JsonVal;

// ===========================================
// USER TYPES
// ===========================================

#[derive(Clone, Debug, PartialEq)]
pub enum MainSqlValue {
    SqlString(String),
    SqlInt(i64),
    SqlFloat(f64),
    SqlBool(bool),
    SqlBytes(Vec<u8>),
    SqlTime(i64),
    SqlDecimal(ipe_runtime::decimal::Decimal),
    SqlMoney(String),
    SqlNull(Box<MainSqlValue>),
}

impl IpeStringify for MainSqlValue {
    fn ipe_show(&self) -> String {
        match self {
            MainSqlValue::SqlString(p0) => format!(
                "SqlString {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
            MainSqlValue::SqlInt(p0) => {
                format!("SqlInt {}", (&ipe_runtime::stringify::Wrap(p0)).dispatch())
            }
            MainSqlValue::SqlFloat(p0) => format!(
                "SqlFloat {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
            MainSqlValue::SqlBool(p0) => {
                format!("SqlBool {}", (&ipe_runtime::stringify::Wrap(p0)).dispatch())
            }
            MainSqlValue::SqlBytes(p0) => format!(
                "SqlBytes {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
            MainSqlValue::SqlTime(p0) => {
                format!("SqlTime {}", (&ipe_runtime::stringify::Wrap(p0)).dispatch())
            }
            MainSqlValue::SqlDecimal(p0) => format!(
                "SqlDecimal {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
            MainSqlValue::SqlMoney(p0) => format!(
                "SqlMoney {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
            MainSqlValue::SqlNull(p0) => {
                format!("SqlNull {}", (&ipe_runtime::stringify::Wrap(p0)).dispatch())
            }
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum MainSqlField {
    SetField(MainSqlValue),
    OmitField,
}

impl IpeStringify for MainSqlField {
    fn ipe_show(&self) -> String {
        match self {
            MainSqlField::SetField(p0) => format!(
                "SetField {}",
                (&ipe_runtime::stringify::Wrap(p0)).dispatch()
            ),
            MainSqlField::OmitField => "OmitField".to_string(),
        }
    }
}

pub type MainProjectionTerm = ipe_runtime::db::ProjectionTerm;

pub type MainProjectionOperand = ipe_runtime::db::ProjectionOperand;

pub type MainArithOp = ipe_runtime::db::ArithOp;

#[derive(Clone, Debug, PartialEq)]
pub struct Rec_ {}

impl IpeStringify for Rec_ {
    fn ipe_show(&self) -> String {
        "{}".to_string()
    }
}

pub struct RecCodecCurrentColumnsFrozenColumnsFrozenTableIndexesOpsPkSpecsTable<T1: 'static> {
    codec: IpeCodecCodec<T1>,
    currentColumns: Vec<IpeDbStoreColumn>,
    frozenColumns: Vec<IpeDbStoreColumn>,
    frozenTable: String,
    indexes: Vec<IpeDbStoreIndexSpec>,
    ops: Vec<IpeDbStoreSchemaOp>,
    pk: IpeResult<ipe_runtime::error::IpeError, IpeDbStorePrimaryKeyDecl>,
    specs: Vec<IpeDbStoreColumnSpec>,
    table: String,
}

impl<T1: Clone + 'static> Clone
    for RecCodecCurrentColumnsFrozenColumnsFrozenTableIndexesOpsPkSpecsTable<T1>
{
    fn clone(&self) -> Self {
        Self {
            codec: self.codec.clone(),
            currentColumns: self.currentColumns.clone(),
            frozenColumns: self.frozenColumns.clone(),
            frozenTable: self.frozenTable.clone(),
            indexes: self.indexes.clone(),
            ops: self.ops.clone(),
            pk: self.pk.clone(),
            specs: self.specs.clone(),
            table: self.table.clone(),
        }
    }
}

impl<T1: IpeStringify + std::fmt::Debug + 'static> IpeStringify
    for RecCodecCurrentColumnsFrozenColumnsFrozenTableIndexesOpsPkSpecsTable<T1>
{
    fn ipe_show(&self) -> String {
        format!(
            "{{{} {} {} {} {} {} {} {} {}}}",
            "<fn>",
            (&ipe_runtime::stringify::Wrap(&self.currentColumns)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.frozenColumns)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.frozenTable)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.indexes)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.ops)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.pk)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.specs)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.table)).dispatch()
        )
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct RecColTypeName {
    colType: IpeCodecColType,
    name: String,
}

impl IpeStringify for RecColTypeName {
    fn ipe_show(&self) -> String {
        format!(
            "{{{} {}}}",
            (&ipe_runtime::stringify::Wrap(&self.colType)).dispatch(),
            (&ipe_runtime::stringify::Wrap(&self.name)).dispatch()
        )
    }
}

pub struct RecEncMkDecShp<T1: 'static> {
    enc: ::std::sync::Arc<dyn Fn(T1) -> JsonVal + Send + Sync + 'static>,
    mkDec: ::std::sync::Arc<dyn Fn(Rec_) -> Decoder<T1> + Send + Sync + 'static>,
    shp: IpeCodecShape,
}

impl<T1: Clone + 'static> Clone for RecEncMkDecShp<T1> {
    fn clone(&self) -> Self {
        Self {
            enc: self.enc.clone(),
            mkDec: self.mkDec.clone(),
            shp: self.shp.clone(),
        }
    }
}

impl<T1: IpeStringify + std::fmt::Debug + 'static> IpeStringify for RecEncMkDecShp<T1> {
    fn ipe_show(&self) -> String {
        format!(
            "{{{} {} {}}}",
            "<fn>",
            "<fn>",
            (&ipe_runtime::stringify::Wrap(&self.shp)).dispatch()
        )
    }
}

impl MainSqlValue {
    /// Convert this `SqlValue` into the runtime-nameable `SqlParam`.
    /// Used by `into_field_param` and by legacy call sites that name
    /// this method directly.  New call sites should prefer the `From`
    /// impl below so the emitter can use the uniform `SqlParam::from`
    /// projection for polymorphic `List a` params.
    pub fn into_sql_param(self) -> ipe_runtime::db::SqlParam {
        match self {
            Self::SqlString(v) => ipe_runtime::db::SqlParam::Text(v),
            Self::SqlInt(v) => ipe_runtime::db::SqlParam::Int(v),
            Self::SqlFloat(v) => ipe_runtime::db::SqlParam::Float(v),
            Self::SqlBool(v) => ipe_runtime::db::SqlParam::Bool(v),
            Self::SqlBytes(v) => ipe_runtime::db::SqlParam::Bytes(v),
            Self::SqlTime(v) => ipe_runtime::db::SqlParam::Int(v),
            Self::SqlDecimal(v) => {
                ipe_runtime::db::SqlParam::Text(ipe_runtime::decimal::decimal_to_string(v))
            }
            Self::SqlMoney(v) => ipe_runtime::db::SqlParam::Text(v),
            Self::SqlNull(inner) => {
                ipe_runtime::db::SqlParam::Null(Box::new(inner.into_sql_param()))
            }
        }
    }
}

/// Allow `SqlParam::from(sql_value)` so the emitter can use the same
/// `ipe_runtime::db::SqlParam::from` projection for ALL element types in
/// the polymorphic `Db.exec`/`query` params list (`List a` where `a` may
/// be `String`, `Int`, `Float`, `Bool`, or `SqlValue`).
impl From<MainSqlValue> for ipe_runtime::db::SqlParam {
    fn from(v: MainSqlValue) -> Self {
        v.into_sql_param()
    }
}

impl MainSqlField {
    pub fn into_field_param(self) -> Option<ipe_runtime::db::SqlParam> {
        match self {
            Self::SetField(v) => Some(v.into_sql_param()),
            Self::OmitField => None,
        }
    }
}

pub use ipe_runtime::error::IpeError;

pub fn str_err(s: &str) -> IpeError {
    IpeError::unexpected(s.to_string())
}

// Recursion guard shim — every user function body opens with
// `let _ipe_recursion_guard = crate::recursion_guard();`, which resolves here.
pub fn recursion_guard() -> ipe_runtime::core::RecursionGuard {
    ipe_runtime::core::recursion_guard()
}

pub type IpeTask<A> = ipe_runtime::IpeTask<IpeError, A>;
pub type Decoder<T> = ipe_runtime::json::Decoder<IpeError, T>;

pub fn ok_res<A>(a: A) -> IpeResult<IpeError, A> {
    ipe_runtime::core::ok_res(a)
}

pub fn task_succeed<A: Send + 'static>(a: A) -> IpeTask<A> {
    ipe_runtime::task::task_succeed(a)
}

// ── System (env) kernels ───────────────────────────────────────────────────
pub fn system_args(_: ()) -> IpeTask<Vec<String>> {
    ipe_runtime::system::system_args(())
}

pub fn system_setenv(key: String, val: String) -> IpeTask<()> {
    ipe_runtime::system::system_setenv(key, val)
}

pub fn system_unsetenv(key: String) -> IpeTask<()> {
    ipe_runtime::system::system_unsetenv(key)
}

// ── Time kernels ───────────────────────────────────────────────────────────
pub fn time_now(_: ()) -> IpeTask<i64> {
    ipe_runtime::time::time_now(())
}

pub fn time_sleep(ms: i64) -> IpeTask<()> {
    ipe_runtime::time::time_sleep(ms)
}

pub fn time_unix_millis(_: ()) -> IpeTask<i64> {
    ipe_runtime::time::time_unix_millis(())
}

// ── Random kernels ─────────────────────────────────────────────────────────
pub fn random_int(lo: i64, hi: i64) -> IpeTask<i64> {
    ipe_runtime::random::random_int(lo, hi)
}

pub fn random_float(lo: f64, hi: f64) -> IpeTask<f64> {
    ipe_runtime::random::random_float(lo, hi)
}

pub fn random_choice(items: Vec<String>) -> IpeTask<String> {
    ipe_runtime::random::random_choice(items)
}

// ── File kernels ───────────────────────────────────────────────────────────
pub fn file_read_file(path: ipe_runtime::path::Path) -> IpeTask<String> {
    ipe_runtime::file::file_read_file(path)
}

pub fn file_write_file(path: ipe_runtime::path::Path, content: String) -> IpeTask<()> {
    ipe_runtime::file::file_write_file(path, content)
}

pub fn file_delete(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_delete(path)
}

// ── Task combinators ───────────────────────────────────────────────────────
pub fn task_fail<A: Send + 'static>(e: IpeError) -> IpeTask<A> {
    ipe_runtime::task::task_fail(e)
}

pub fn task_map<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> B + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<B> {
    ipe_runtime::task::task_map(f, t)
}

pub fn task_and_then<A: Send + 'static, B: Send + 'static>(
    t: IpeTask<A>,
    f: Box<dyn FnOnce(A) -> IpeTask<B> + Send + 'static>,
) -> IpeTask<B> {
    ipe_runtime::task::task_and_then(t, f)
}

pub fn task_map_error<A: Send + 'static>(
    f: Box<dyn Fn(IpeError) -> IpeError + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<A> {
    ipe_runtime::task::task_map_error(f, t)
}

pub fn task_on_error<A: Send + 'static>(
    f: Box<dyn FnOnce(IpeError) -> IpeTask<A> + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<A> {
    ipe_runtime::task::task_on_error(f, t)
}

pub fn task_from_result<A: Send + 'static>(r: IpeResult<IpeError, A>) -> IpeTask<A> {
    ipe_runtime::task::task_from_result(r)
}

pub fn task_and_then_result<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> IpeResult<IpeError, B> + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<B> {
    ipe_runtime::task::task_and_then_result(f, t)
}

pub fn task_sequence<A: Send + 'static>(tasks: Vec<IpeTask<A>>) -> IpeTask<Vec<A>> {
    ipe_runtime::task::task_sequence(tasks)
}

pub fn task_parallel<A: Send + 'static>(tasks: Vec<IpeTask<A>>) -> IpeTask<Vec<A>> {
    ipe_runtime::task::task_parallel(tasks)
}

pub fn task_run<A: Send + 'static>(t: IpeTask<A>) -> IpeResult<IpeError, A> {
    ipe_runtime::task::task_run(t)
}

// ── Io kernels ─────────────────────────────────────────────────────────────
pub fn io_read_line(_: ()) -> IpeTask<String> {
    ipe_runtime::io::io_read_line(())
}

pub fn io_write_stdout(s: String) -> IpeTask<()> {
    ipe_runtime::io::io_write_stdout(s)
}

pub fn io_write_stderr(s: String) -> IpeTask<()> {
    ipe_runtime::io::io_write_stderr(s)
}

pub fn io_println(msg: String) -> IpeTask<()> {
    ipe_runtime::io::io_println(msg)
}

pub fn io_eprintln(msg: String) -> IpeTask<()> {
    ipe_runtime::io::io_eprintln(msg)
}

// ── System kernels ─────────────────────────────────────────────────────────
pub fn system_getenv(key: String) -> IpeTask<String> {
    ipe_runtime::system::system_getenv(key)
}

pub fn system_getenv_or(key: String, default: String) -> String {
    ipe_runtime::system::system_getenv_or(key, default)
}

pub fn system_get_arg(n: i64) -> IpeTask<IpeMaybe<String>> {
    ipe_runtime::system::system_get_arg(n)
}

pub fn system_getenv_int(key: String) -> IpeTask<i64> {
    ipe_runtime::system::system_getenv_int(key)
}

pub fn system_getenv_bool(key: String) -> IpeTask<bool> {
    ipe_runtime::system::system_getenv_bool(key)
}

pub fn system_cwd(_: ()) -> IpeTask<String> {
    ipe_runtime::system::system_cwd(())
}

pub fn system_getcwd(_: ()) -> IpeTask<String> {
    ipe_runtime::system::system_getcwd(())
}

pub fn system_load_env(_: ()) -> IpeTask<()> {
    ipe_runtime::system::system_load_env(())
}

pub fn system_exit(code: i64) -> ! {
    ipe_runtime::system::system_exit(code)
}

// ── File kernels ───────────────────────────────────────────────────────────
pub fn file_exists(path: ipe_runtime::path::Path) -> IpeTask<bool> {
    ipe_runtime::file::file_exists(path)
}

pub fn file_remove(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_remove(path)
}

pub fn file_mkdir_all(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_mkdir_all(path)
}

pub fn file_read_file_limit(path: ipe_runtime::path::Path, limit: i64) -> IpeTask<String> {
    ipe_runtime::file::file_read_file_limit(path, limit)
}

pub fn file_read_file_bytes(path: ipe_runtime::path::Path) -> IpeTask<Vec<i64>> {
    ipe_runtime::file::file_read_file_bytes(path)
}

pub fn file_append(path: ipe_runtime::path::Path, content: String) -> IpeTask<()> {
    ipe_runtime::file::file_append(path, content)
}

pub fn file_read_dir(path: ipe_runtime::path::Path) -> IpeTask<Vec<String>> {
    ipe_runtime::file::file_read_dir(path)
}

pub fn file_is_dir(path: ipe_runtime::path::Path) -> IpeTask<bool> {
    ipe_runtime::file::file_is_dir(path)
}

pub fn file_temp_file(prefix: String) -> IpeTask<String> {
    ipe_runtime::file::file_temp_file(prefix)
}

pub fn file_temp_dir(prefix: String) -> IpeTask<String> {
    ipe_runtime::file::file_temp_dir(prefix)
}

pub fn file_copy(src: ipe_runtime::path::Path, dst: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_copy(src, dst)
}

pub fn file_rename(src: ipe_runtime::path::Path, dst: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_rename(src, dst)
}

// ── Crypto (entropy) kernels ───────────────────────────────────────────────
pub fn crypto_random_bytes(n: i64) -> IpeTask<String> {
    ipe_runtime::crypto_core::crypto_random_bytes(n)
}

pub fn crypto_random_token(n: i64) -> IpeTask<String> {
    ipe_runtime::crypto_core::crypto_random_token(n)
}

// List helpers
pub fn list_map_consume<T0, T1>(f: impl Fn(T0) -> T1, list: Vec<T0>) -> Vec<T1> {
    list.into_iter().map(f).collect()
}

// ===========================================
// ENTRY POINT
// ===========================================

fn main() {
    // Synchronous-panic gate (parity: rt.LogPanicAndExit) —
    // classify an escaping panic (div-by-zero / index-OOB /
    // overflow) into a Ipe error + exit 1, not a raw Rust backtrace.
    ipe_runtime::core::install_panic_classifier();
    match block_on(ipe_main()) {
        IpeResult::Ok(_) => (),
        IpeResult::Err(e) => {
            ipe_runtime::core::eprint_task_error(&e.to_string());
            std::process::exit(1);
        }
    }
}

#[path = "ipe_mods/ipe_mod_ipe_codec.rs"]
mod ipe_mod_ipe_codec;
pub(crate) use ipe_mod_ipe_codec::*;

#[path = "ipe_mods/ipe_mod_ipe_db_codec.rs"]
mod ipe_mod_ipe_db_codec;
pub(crate) use ipe_mod_ipe_db_codec::*;

#[path = "ipe_mods/ipe_mod_ipe_db_store.rs"]
mod ipe_mod_ipe_db_store;
pub(crate) use ipe_mod_ipe_db_store::*;

#[path = "ipe_mods/ipe_mod_main.rs"]
mod ipe_mod_main;
pub(crate) use ipe_mod_main::*;
