// GENERATED by Ipê — do not edit
pub mod basics;
pub mod cache;
pub mod color;
pub mod length;
pub mod char_kernel;
pub mod char_category;
pub mod config;
// The dev-loop control channel (`ControlFrame` wire + loopback `server`).
// Gated to match its source declaration: present only under a dev-loop surface
// (`web` references `control::AppearancePatch`; `debugger` drives it, and both
// compile the tokio `control::server` accept-loop), absent from a release build.
// The parent-side `control-wire` codec-only feature is a CLI concern, never
// selected for an emitted project. Its serde/ct_eq dependencies are satisfied by
// exactly those features.
#[cfg(any(feature = "web", feature = "debugger", feature = "control-wire"))]
pub mod control;
pub mod core;
pub mod ct_eq;
pub mod crypto_core;
pub mod debug;
pub mod decimal;
pub mod dict;
pub mod error;
pub mod escape;
pub mod ffi_polyfills;
pub mod file;
pub mod http_header;
pub mod io;
pub mod json;
pub mod bitwise;
pub mod list;
pub mod log;
pub mod math;
pub mod money;
pub mod home_core;
pub mod scratch_core;
pub mod scratch_host;
pub mod path_core;
pub mod path;
pub mod redact;
pub mod secret;
pub mod app_config;
pub mod set;
pub mod string;
pub mod stringify;
pub mod system;
pub mod task;
pub mod threads;
pub mod telemetry;
pub mod csp;
pub mod time;
pub mod trace;
pub use basics::*;
pub use cache::*;
pub use color::*;
pub use length::*;
pub use char_kernel::*;
pub use char_category::*;
pub use config::*;
pub use core::*;
pub use crypto_core::*;
pub use debug::*;
pub use decimal::*;
pub use dict::*;
pub use error::*;
pub use ffi_polyfills::*;
pub use file::*;
pub use io::*;
pub use json::*;
pub use bitwise::*;
pub use list::*;
pub use log::*;
pub use math::*;
pub use money::*;
pub use path::*;
pub use secret::*;
pub use app_config::*;
pub use set::*;
pub use string::*;
pub use stringify::*;
pub use system::*;
pub use task::*;
pub use time::*;
pub use trace::*;
