[package]
name = "regen-goldens"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "regen-goldens"
path = "src/main.rs"

[dependencies]
ipe = { path = "../../src/ipe-cli" }
ipe_docs = { path = "../../src/ipe-docs" }
e2e-support = { path = "../e2e-support" }

[lints]
workspace = true
