// Generated by Ipê (Rust target)
#![allow(unused, non_snake_case)]

#[cfg(feature = "alloc_dlmalloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: dlmalloc::GlobalDlmalloc = dlmalloc::GlobalDlmalloc;

#[cfg(feature = "alloc_mimalloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub use ipe_runtime::*;

use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fmt;
use std::future::Future;
use std::future::ready;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll, Wake, Waker};

// Basic types
type IpeInt = i64;
type IpeFloat = f64;
type IpeBool = bool;
type IpeString = String;

// ===========================================
// USER TYPES
// ===========================================

#[derive(Clone, Debug, PartialEq)]
pub struct RecXY {
    x: i64,
    y: i64,
}

impl IpeStringify for RecXY {
    fn ipe_show(&self) -> String {
        format!(
            "{{{} {}}}",
            IpeStringify::ipe_show(&self.x),
            IpeStringify::ipe_show(&self.y)
        )
    }
}

pub use ipe_runtime::error::IpeError;

pub fn str_err(s: &str) -> IpeError {
    IpeError::unexpected(s.to_string())
}

// Recursion guard shim — every user function body opens with
// `let _ipe_recursion_guard = crate::recursion_guard();`, which resolves here.
pub fn recursion_guard() -> ipe_runtime::core::RecursionGuard {
    ipe_runtime::core::recursion_guard()
}

pub type IpeTask<A> = ipe_runtime::IpeTask<IpeError, A>;

pub fn ok_res<A>(a: A) -> IpeResult<IpeError, A> {
    ipe_runtime::core::ok_res(a)
}

pub fn task_succeed<A: Send + 'static>(a: A) -> IpeTask<A> {
    ipe_runtime::task::task_succeed(a)
}

// ── System (env) kernels ───────────────────────────────────────────────────
pub fn system_args(_: ()) -> IpeTask<Vec<String>> {
    ipe_runtime::system::system_args(())
}

pub fn system_setenv(key: String, val: String) -> IpeTask<()> {
    ipe_runtime::system::system_setenv(key, val)
}

pub fn system_unsetenv(key: String) -> IpeTask<()> {
    ipe_runtime::system::system_unsetenv(key)
}

// ── File kernels ───────────────────────────────────────────────────────────
pub fn file_read_file(path: ipe_runtime::path::Path) -> IpeTask<String> {
    ipe_runtime::file::file_read_file(path)
}

pub fn file_write_file(path: ipe_runtime::path::Path, content: String) -> IpeTask<()> {
    ipe_runtime::file::file_write_file(path, content)
}

pub fn file_delete(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_delete(path)
}

// ── Task combinators ───────────────────────────────────────────────────────
pub fn task_fail<A: Send + 'static>(e: IpeError) -> IpeTask<A> {
    ipe_runtime::task::task_fail(e)
}

pub fn task_map<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> B + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<B> {
    ipe_runtime::task::task_map(f, t)
}

pub fn task_and_then<A: Send + 'static, B: Send + 'static>(
    t: IpeTask<A>,
    f: Box<dyn FnOnce(A) -> IpeTask<B> + Send + 'static>,
) -> IpeTask<B> {
    ipe_runtime::task::task_and_then(t, f)
}

pub fn task_map_error<A: Send + 'static>(
    f: Box<dyn Fn(IpeError) -> IpeError + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<A> {
    ipe_runtime::task::task_map_error(f, t)
}

pub fn task_on_error<A: Send + 'static>(
    f: Box<dyn FnOnce(IpeError) -> IpeTask<A> + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<A> {
    ipe_runtime::task::task_on_error(f, t)
}

pub fn task_from_result<A: Send + 'static>(r: IpeResult<IpeError, A>) -> IpeTask<A> {
    ipe_runtime::task::task_from_result(r)
}

pub fn task_and_then_result<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> IpeResult<IpeError, B> + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<B> {
    ipe_runtime::task::task_and_then_result(f, t)
}

pub fn task_sequence<A: Send + 'static>(tasks: Vec<IpeTask<A>>) -> IpeTask<Vec<A>> {
    ipe_runtime::task::task_sequence(tasks)
}

pub fn task_parallel<A: Send + 'static>(tasks: Vec<IpeTask<A>>) -> IpeTask<Vec<A>> {
    ipe_runtime::task::task_parallel(tasks)
}

pub fn task_run<A: Send + 'static>(t: IpeTask<A>) -> IpeResult<IpeError, A> {
    ipe_runtime::task::task_run(t)
}

// ── Io kernels ─────────────────────────────────────────────────────────────
pub fn io_read_line(_: ()) -> IpeTask<String> {
    ipe_runtime::io::io_read_line(())
}

pub fn io_write_stdout(s: String) -> IpeTask<()> {
    ipe_runtime::io::io_write_stdout(s)
}

pub fn io_write_stderr(s: String) -> IpeTask<()> {
    ipe_runtime::io::io_write_stderr(s)
}

pub fn io_println(msg: String) -> IpeTask<()> {
    ipe_runtime::io::io_println(msg)
}

pub fn io_eprintln(msg: String) -> IpeTask<()> {
    ipe_runtime::io::io_eprintln(msg)
}

// ── System kernels ─────────────────────────────────────────────────────────
pub fn system_getenv(key: String) -> IpeTask<String> {
    ipe_runtime::system::system_getenv(key)
}

pub fn system_getenv_or(key: String, default: String) -> String {
    ipe_runtime::system::system_getenv_or(key, default)
}

pub fn system_get_arg(n: i64) -> IpeTask<IpeMaybe<String>> {
    ipe_runtime::system::system_get_arg(n)
}

pub fn system_getenv_int(key: String) -> IpeTask<i64> {
    ipe_runtime::system::system_getenv_int(key)
}

pub fn system_getenv_bool(key: String) -> IpeTask<bool> {
    ipe_runtime::system::system_getenv_bool(key)
}

pub fn system_cwd(_: ()) -> IpeTask<String> {
    ipe_runtime::system::system_cwd(())
}

pub fn system_getcwd(_: ()) -> IpeTask<String> {
    ipe_runtime::system::system_getcwd(())
}

pub fn system_load_env(_: ()) -> IpeTask<()> {
    ipe_runtime::system::system_load_env(())
}

pub fn system_exit(code: i64) -> ! {
    ipe_runtime::system::system_exit(code)
}

// ── File kernels ───────────────────────────────────────────────────────────
pub fn file_exists(path: ipe_runtime::path::Path) -> IpeTask<bool> {
    ipe_runtime::file::file_exists(path)
}

pub fn file_remove(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_remove(path)
}

pub fn file_mkdir_all(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_mkdir_all(path)
}

pub fn file_read_file_limit(path: ipe_runtime::path::Path, limit: i64) -> IpeTask<String> {
    ipe_runtime::file::file_read_file_limit(path, limit)
}

pub fn file_read_file_bytes(path: ipe_runtime::path::Path) -> IpeTask<Vec<i64>> {
    ipe_runtime::file::file_read_file_bytes(path)
}

pub fn file_append(path: ipe_runtime::path::Path, content: String) -> IpeTask<()> {
    ipe_runtime::file::file_append(path, content)
}

pub fn file_read_dir(path: ipe_runtime::path::Path) -> IpeTask<Vec<String>> {
    ipe_runtime::file::file_read_dir(path)
}

pub fn file_is_dir(path: ipe_runtime::path::Path) -> IpeTask<bool> {
    ipe_runtime::file::file_is_dir(path)
}

pub fn file_temp_file(prefix: String) -> IpeTask<String> {
    ipe_runtime::file::file_temp_file(prefix)
}

pub fn file_temp_dir(prefix: String) -> IpeTask<String> {
    ipe_runtime::file::file_temp_dir(prefix)
}

pub fn file_copy(src: ipe_runtime::path::Path, dst: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_copy(src, dst)
}

pub fn file_rename(src: ipe_runtime::path::Path, dst: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_rename(src, dst)
}

pub fn main_apply_i<FN0: Fn(i64) -> i64 + Send + Sync + 'static>(f: FN0, x: i64) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    (f)(x)
}

pub fn main_apply_p<FN0: Fn((i64, i64)) -> i64 + Send + Sync + 'static>(
    f: FN0,
    p: (i64, i64),
) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    (f)(p)
}

pub fn main_apply_r<FN0: Fn(RecXY) -> i64 + Send + Sync + 'static>(f: FN0, r: RecXY) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    (f)(r)
}

pub fn main_apply_m<FN0: Fn(i64, i64, (i64, i64)) -> i64 + Send + Sync + 'static>(f: FN0) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    (f)(100i64, 3i64, (4i64, 5i64))
}

pub fn main_ignore_arg(arg_0: i64) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    7i64
}

pub fn main_sum_pair(arg_1: (i64, i64)) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    ({
        let (a, b) = arg_1;
        ipe_runtime::math::ipe_int_add(a, b)
    })
}

pub fn main_get_y(arg_2: RecXY) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    ({
        let RecXY { x: _, y, .. } = arg_2;
        y
    })
}

pub fn main_first_of_alias(arg_3: (i64, i64)) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    ({
        let whole = arg_3;
        let (a, b) = whole.clone();
        a
    })
}

pub fn main_countdown(arg_4: (i64, i64)) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    let mut arg_4 = arg_4;
    loop {
        let (n, acc) = arg_4;
        match n {
            0 => {
                return acc;
            }
            _ => {
                let __tco_0 = (ipe_runtime::math::ipe_int_sub(n, 1i64), ipe_runtime::math::ipe_int_add(acc, n));
                arg_4 = __tco_0;
                continue;
            }
        }
    }
}

pub fn ipe_main() -> IpeTask<()> {
    let _ipe_recursion_guard = crate::recursion_guard();
    io_println(string_from_int(ipe_runtime::math::ipe_int_add(
        ipe_runtime::math::ipe_int_add(
            ipe_runtime::math::ipe_int_add(
                ipe_runtime::math::ipe_int_add(
                    ipe_runtime::math::ipe_int_add(
                        ipe_runtime::math::ipe_int_add(
                            ipe_runtime::math::ipe_int_add(
                                ipe_runtime::math::ipe_int_add(
                                    crate::main_apply_i(move |arg_5: i64| -> i64 { 42i64 }, 0i64),
                                    crate::main_apply_p(
                                        move |arg_6: (i64, i64)| -> i64 {
                                            ({
                                                let (a, b) = arg_6;
                                                ipe_runtime::math::ipe_int_add(a, b)
                                            })
                                        },
                                        (1i64, 2i64),
                                    ),
                                ),
                                crate::main_apply_r(
                                    move |arg_7: RecXY| -> i64 {
                                        ({
                                            let RecXY { x, y: _, .. } = arg_7;
                                            x
                                        })
                                    },
                                    RecXY { x: 10i64, y: 5i64 },
                                ),
                            ),
                            crate::main_apply_m(
                                move |arg_8: i64, x: i64, arg_9: (i64, i64)| -> i64 {
                                    ({
                                        let (a, b) = arg_9;
                                        ipe_runtime::math::ipe_int_add(
                                            ipe_runtime::math::ipe_int_add(x, a),
                                            b,
                                        )
                                    })
                                },
                            ),
                        ),
                        crate::main_ignore_arg(99i64),
                    ),
                    crate::main_sum_pair((4i64, 5i64)),
                ),
                crate::main_get_y(RecXY { x: 1i64, y: 8i64 }),
            ),
            crate::main_first_of_alias((6i64, 7i64)),
        ),
        crate::main_countdown((5i64, 0i64)),
    )))
}

// List helpers
pub fn list_map_consume<T0, T1>(f: impl Fn(T0) -> T1, list: Vec<T0>) -> Vec<T1> {
    list.into_iter().map(f).collect()
}

// ===========================================
// ENTRY POINT
// ===========================================

fn main() {
    // Synchronous-panic gate (parity: rt.LogPanicAndExit) —
    // classify an escaping panic (div-by-zero / index-OOB /
    // overflow) into a Ipe error + exit 1, not a raw Rust backtrace.
    ipe_runtime::core::install_panic_classifier();
    match block_on(ipe_main()) {
        IpeResult::Ok(_) => (),
        IpeResult::Err(e) => {
            ipe_runtime::core::eprint_task_error(&e.to_string());
            std::process::exit(1);
        }
    }
}
