use crate::*;

#[derive(Clone, Debug, PartialEq)]
pub(crate) enum IpeMoneyCurrency {
    USD,
    EUR,
    GBP,
    JPY,
    CHF,
    AUD,
    CAD,
    NZD,
    SEK,
    NOK,
    DKK,
    CNY,
    HKD,
    SGD,
    KRW,
    TWD,
    INR,
    THB,
    MYR,
    IDR,
    PHP,
    VND,
    BRL,
    MXN,
    ARS,
    CLP,
    ZAR,
    TRY,
    RUB,
    UAH,
    PLN,
    CZK,
    HUF,
    RON,
    BGN,
    AED,
    SAR,
    QAR,
    KWD,
    BHD,
    OMR,
    JOD,
    ILS,
    EGP,
    NGN,
    KES,
    GHS,
    MAD,
    TND,
    DZD,
    PKR,
    BDT,
    LKR,
    NPR,
    BTC,
    ETH,
    USDT,
    USDC,
    CurrencyRaw(String),
}

impl IpeStringify for IpeMoneyCurrency {
    fn ipe_show(&self) -> String {
        match self {
            IpeMoneyCurrency::USD => "USD".to_string(),
            IpeMoneyCurrency::EUR => "EUR".to_string(),
            IpeMoneyCurrency::GBP => "GBP".to_string(),
            IpeMoneyCurrency::JPY => "JPY".to_string(),
            IpeMoneyCurrency::CHF => "CHF".to_string(),
            IpeMoneyCurrency::AUD => "AUD".to_string(),
            IpeMoneyCurrency::CAD => "CAD".to_string(),
            IpeMoneyCurrency::NZD => "NZD".to_string(),
            IpeMoneyCurrency::SEK => "SEK".to_string(),
            IpeMoneyCurrency::NOK => "NOK".to_string(),
            IpeMoneyCurrency::DKK => "DKK".to_string(),
            IpeMoneyCurrency::CNY => "CNY".to_string(),
            IpeMoneyCurrency::HKD => "HKD".to_string(),
            IpeMoneyCurrency::SGD => "SGD".to_string(),
            IpeMoneyCurrency::KRW => "KRW".to_string(),
            IpeMoneyCurrency::TWD => "TWD".to_string(),
            IpeMoneyCurrency::INR => "INR".to_string(),
            IpeMoneyCurrency::THB => "THB".to_string(),
            IpeMoneyCurrency::MYR => "MYR".to_string(),
            IpeMoneyCurrency::IDR => "IDR".to_string(),
            IpeMoneyCurrency::PHP => "PHP".to_string(),
            IpeMoneyCurrency::VND => "VND".to_string(),
            IpeMoneyCurrency::BRL => "BRL".to_string(),
            IpeMoneyCurrency::MXN => "MXN".to_string(),
            IpeMoneyCurrency::ARS => "ARS".to_string(),
            IpeMoneyCurrency::CLP => "CLP".to_string(),
            IpeMoneyCurrency::ZAR => "ZAR".to_string(),
            IpeMoneyCurrency::TRY => "TRY".to_string(),
            IpeMoneyCurrency::RUB => "RUB".to_string(),
            IpeMoneyCurrency::UAH => "UAH".to_string(),
            IpeMoneyCurrency::PLN => "PLN".to_string(),
            IpeMoneyCurrency::CZK => "CZK".to_string(),
            IpeMoneyCurrency::HUF => "HUF".to_string(),
            IpeMoneyCurrency::RON => "RON".to_string(),
            IpeMoneyCurrency::BGN => "BGN".to_string(),
            IpeMoneyCurrency::AED => "AED".to_string(),
            IpeMoneyCurrency::SAR => "SAR".to_string(),
            IpeMoneyCurrency::QAR => "QAR".to_string(),
            IpeMoneyCurrency::KWD => "KWD".to_string(),
            IpeMoneyCurrency::BHD => "BHD".to_string(),
            IpeMoneyCurrency::OMR => "OMR".to_string(),
            IpeMoneyCurrency::JOD => "JOD".to_string(),
            IpeMoneyCurrency::ILS => "ILS".to_string(),
            IpeMoneyCurrency::EGP => "EGP".to_string(),
            IpeMoneyCurrency::NGN => "NGN".to_string(),
            IpeMoneyCurrency::KES => "KES".to_string(),
            IpeMoneyCurrency::GHS => "GHS".to_string(),
            IpeMoneyCurrency::MAD => "MAD".to_string(),
            IpeMoneyCurrency::TND => "TND".to_string(),
            IpeMoneyCurrency::DZD => "DZD".to_string(),
            IpeMoneyCurrency::PKR => "PKR".to_string(),
            IpeMoneyCurrency::BDT => "BDT".to_string(),
            IpeMoneyCurrency::LKR => "LKR".to_string(),
            IpeMoneyCurrency::NPR => "NPR".to_string(),
            IpeMoneyCurrency::BTC => "BTC".to_string(),
            IpeMoneyCurrency::ETH => "ETH".to_string(),
            IpeMoneyCurrency::USDT => "USDT".to_string(),
            IpeMoneyCurrency::USDC => "USDC".to_string(),
            IpeMoneyCurrency::CurrencyRaw(p0) => {
                format!("CurrencyRaw {}", IpeStringify::ipe_show(p0))
            }
        }
    }
}

pub(crate) fn user_ipe_money_currency_code(c: IpeMoneyCurrency) -> String {
    let _ipe_recursion_guard = crate::recursion_guard();
    match c {
        IpeMoneyCurrency::USD => "USD".to_string(),
        IpeMoneyCurrency::EUR => "EUR".to_string(),
        IpeMoneyCurrency::GBP => "GBP".to_string(),
        IpeMoneyCurrency::JPY => "JPY".to_string(),
        IpeMoneyCurrency::CHF => "CHF".to_string(),
        IpeMoneyCurrency::AUD => "AUD".to_string(),
        IpeMoneyCurrency::CAD => "CAD".to_string(),
        IpeMoneyCurrency::NZD => "NZD".to_string(),
        IpeMoneyCurrency::SEK => "SEK".to_string(),
        IpeMoneyCurrency::NOK => "NOK".to_string(),
        IpeMoneyCurrency::DKK => "DKK".to_string(),
        IpeMoneyCurrency::CNY => "CNY".to_string(),
        IpeMoneyCurrency::HKD => "HKD".to_string(),
        IpeMoneyCurrency::SGD => "SGD".to_string(),
        IpeMoneyCurrency::KRW => "KRW".to_string(),
        IpeMoneyCurrency::TWD => "TWD".to_string(),
        IpeMoneyCurrency::INR => "INR".to_string(),
        IpeMoneyCurrency::THB => "THB".to_string(),
        IpeMoneyCurrency::MYR => "MYR".to_string(),
        IpeMoneyCurrency::IDR => "IDR".to_string(),
        IpeMoneyCurrency::PHP => "PHP".to_string(),
        IpeMoneyCurrency::VND => "VND".to_string(),
        IpeMoneyCurrency::BRL => "BRL".to_string(),
        IpeMoneyCurrency::MXN => "MXN".to_string(),
        IpeMoneyCurrency::ARS => "ARS".to_string(),
        IpeMoneyCurrency::CLP => "CLP".to_string(),
        IpeMoneyCurrency::ZAR => "ZAR".to_string(),
        IpeMoneyCurrency::TRY => "TRY".to_string(),
        IpeMoneyCurrency::RUB => "RUB".to_string(),
        IpeMoneyCurrency::UAH => "UAH".to_string(),
        IpeMoneyCurrency::PLN => "PLN".to_string(),
        IpeMoneyCurrency::CZK => "CZK".to_string(),
        IpeMoneyCurrency::HUF => "HUF".to_string(),
        IpeMoneyCurrency::RON => "RON".to_string(),
        IpeMoneyCurrency::BGN => "BGN".to_string(),
        IpeMoneyCurrency::AED => "AED".to_string(),
        IpeMoneyCurrency::SAR => "SAR".to_string(),
        IpeMoneyCurrency::QAR => "QAR".to_string(),
        IpeMoneyCurrency::KWD => "KWD".to_string(),
        IpeMoneyCurrency::BHD => "BHD".to_string(),
        IpeMoneyCurrency::OMR => "OMR".to_string(),
        IpeMoneyCurrency::JOD => "JOD".to_string(),
        IpeMoneyCurrency::ILS => "ILS".to_string(),
        IpeMoneyCurrency::EGP => "EGP".to_string(),
        IpeMoneyCurrency::NGN => "NGN".to_string(),
        IpeMoneyCurrency::KES => "KES".to_string(),
        IpeMoneyCurrency::GHS => "GHS".to_string(),
        IpeMoneyCurrency::MAD => "MAD".to_string(),
        IpeMoneyCurrency::TND => "TND".to_string(),
        IpeMoneyCurrency::DZD => "DZD".to_string(),
        IpeMoneyCurrency::PKR => "PKR".to_string(),
        IpeMoneyCurrency::BDT => "BDT".to_string(),
        IpeMoneyCurrency::LKR => "LKR".to_string(),
        IpeMoneyCurrency::NPR => "NPR".to_string(),
        IpeMoneyCurrency::BTC => "BTC".to_string(),
        IpeMoneyCurrency::ETH => "ETH".to_string(),
        IpeMoneyCurrency::USDT => "USDT".to_string(),
        IpeMoneyCurrency::USDC => "USDC".to_string(),
        IpeMoneyCurrency::CurrencyRaw(s) => s,
    }
}

pub(crate) fn user_ipe_money_parse_currency(code: String) -> IpeMaybe<IpeMoneyCurrency> {
    let _ipe_recursion_guard = crate::recursion_guard();
    match (string_to_upper(string_trim(code))).as_str() {
        "USD" => IpeMaybe::Just(IpeMoneyCurrency::USD),
        "EUR" => IpeMaybe::Just(IpeMoneyCurrency::EUR),
        "GBP" => IpeMaybe::Just(IpeMoneyCurrency::GBP),
        "JPY" => IpeMaybe::Just(IpeMoneyCurrency::JPY),
        "CHF" => IpeMaybe::Just(IpeMoneyCurrency::CHF),
        "AUD" => IpeMaybe::Just(IpeMoneyCurrency::AUD),
        "CAD" => IpeMaybe::Just(IpeMoneyCurrency::CAD),
        "NZD" => IpeMaybe::Just(IpeMoneyCurrency::NZD),
        "SEK" => IpeMaybe::Just(IpeMoneyCurrency::SEK),
        "NOK" => IpeMaybe::Just(IpeMoneyCurrency::NOK),
        "DKK" => IpeMaybe::Just(IpeMoneyCurrency::DKK),
        "CNY" => IpeMaybe::Just(IpeMoneyCurrency::CNY),
        "HKD" => IpeMaybe::Just(IpeMoneyCurrency::HKD),
        "SGD" => IpeMaybe::Just(IpeMoneyCurrency::SGD),
        "KRW" => IpeMaybe::Just(IpeMoneyCurrency::KRW),
        "TWD" => IpeMaybe::Just(IpeMoneyCurrency::TWD),
        "INR" => IpeMaybe::Just(IpeMoneyCurrency::INR),
        "THB" => IpeMaybe::Just(IpeMoneyCurrency::THB),
        "MYR" => IpeMaybe::Just(IpeMoneyCurrency::MYR),
        "IDR" => IpeMaybe::Just(IpeMoneyCurrency::IDR),
        "PHP" => IpeMaybe::Just(IpeMoneyCurrency::PHP),
        "VND" => IpeMaybe::Just(IpeMoneyCurrency::VND),
        "BRL" => IpeMaybe::Just(IpeMoneyCurrency::BRL),
        "MXN" => IpeMaybe::Just(IpeMoneyCurrency::MXN),
        "ARS" => IpeMaybe::Just(IpeMoneyCurrency::ARS),
        "CLP" => IpeMaybe::Just(IpeMoneyCurrency::CLP),
        "ZAR" => IpeMaybe::Just(IpeMoneyCurrency::ZAR),
        "TRY" => IpeMaybe::Just(IpeMoneyCurrency::TRY),
        "RUB" => IpeMaybe::Just(IpeMoneyCurrency::RUB),
        "UAH" => IpeMaybe::Just(IpeMoneyCurrency::UAH),
        "PLN" => IpeMaybe::Just(IpeMoneyCurrency::PLN),
        "CZK" => IpeMaybe::Just(IpeMoneyCurrency::CZK),
        "HUF" => IpeMaybe::Just(IpeMoneyCurrency::HUF),
        "RON" => IpeMaybe::Just(IpeMoneyCurrency::RON),
        "BGN" => IpeMaybe::Just(IpeMoneyCurrency::BGN),
        "AED" => IpeMaybe::Just(IpeMoneyCurrency::AED),
        "SAR" => IpeMaybe::Just(IpeMoneyCurrency::SAR),
        "QAR" => IpeMaybe::Just(IpeMoneyCurrency::QAR),
        "KWD" => IpeMaybe::Just(IpeMoneyCurrency::KWD),
        "BHD" => IpeMaybe::Just(IpeMoneyCurrency::BHD),
        "OMR" => IpeMaybe::Just(IpeMoneyCurrency::OMR),
        "JOD" => IpeMaybe::Just(IpeMoneyCurrency::JOD),
        "ILS" => IpeMaybe::Just(IpeMoneyCurrency::ILS),
        "EGP" => IpeMaybe::Just(IpeMoneyCurrency::EGP),
        "NGN" => IpeMaybe::Just(IpeMoneyCurrency::NGN),
        "KES" => IpeMaybe::Just(IpeMoneyCurrency::KES),
        "GHS" => IpeMaybe::Just(IpeMoneyCurrency::GHS),
        "MAD" => IpeMaybe::Just(IpeMoneyCurrency::MAD),
        "TND" => IpeMaybe::Just(IpeMoneyCurrency::TND),
        "DZD" => IpeMaybe::Just(IpeMoneyCurrency::DZD),
        "PKR" => IpeMaybe::Just(IpeMoneyCurrency::PKR),
        "BDT" => IpeMaybe::Just(IpeMoneyCurrency::BDT),
        "LKR" => IpeMaybe::Just(IpeMoneyCurrency::LKR),
        "NPR" => IpeMaybe::Just(IpeMoneyCurrency::NPR),
        "BTC" => IpeMaybe::Just(IpeMoneyCurrency::BTC),
        "ETH" => IpeMaybe::Just(IpeMoneyCurrency::ETH),
        "USDT" => IpeMaybe::Just(IpeMoneyCurrency::USDT),
        "USDC" => IpeMaybe::Just(IpeMoneyCurrency::USDC),
        _ => IpeMaybe::Nothing,
    }
}
