// Generated by Ipê (Rust target)
#![allow(unused, non_snake_case)]

#[cfg(feature = "alloc_dlmalloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: dlmalloc::GlobalDlmalloc = dlmalloc::GlobalDlmalloc;

#[cfg(feature = "alloc_mimalloc")]
#[global_allocator]
static IPE_GLOBAL_ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub use ipe_runtime::*;

use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fmt;
use std::future::Future;
use std::future::ready;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll, Wake, Waker};

// Basic types
type IpeInt = i64;
type IpeFloat = f64;
type IpeBool = bool;
type IpeString = String;

// ===========================================
// USER TYPES
// ===========================================

pub use ipe_runtime::error::IpeError;

pub fn str_err(s: &str) -> IpeError {
    IpeError::unexpected(s.to_string())
}

// Recursion guard shim — every user function body opens with
// `let _ipe_recursion_guard = crate::recursion_guard();`, which resolves here.
pub fn recursion_guard() -> ipe_runtime::core::RecursionGuard {
    ipe_runtime::core::recursion_guard()
}

pub type IpeTask<A> = ipe_runtime::IpeTask<IpeError, A>;

pub fn ok_res<A>(a: A) -> IpeResult<IpeError, A> {
    ipe_runtime::core::ok_res(a)
}

pub fn task_succeed<A: Send + 'static>(a: A) -> IpeTask<A> {
    ipe_runtime::task::task_succeed(a)
}

// ── System (env) kernels ───────────────────────────────────────────────────
pub fn system_args(_: ()) -> IpeTask<Vec<String>> {
    ipe_runtime::system::system_args(())
}

pub fn system_setenv(key: String, val: String) -> IpeTask<()> {
    ipe_runtime::system::system_setenv(key, val)
}

pub fn system_unsetenv(key: String) -> IpeTask<()> {
    ipe_runtime::system::system_unsetenv(key)
}

// ── Random kernels ─────────────────────────────────────────────────────────
pub fn random_int(lo: i64, hi: i64) -> IpeTask<i64> {
    ipe_runtime::random::random_int(lo, hi)
}

pub fn random_float(lo: f64, hi: f64) -> IpeTask<f64> {
    ipe_runtime::random::random_float(lo, hi)
}

pub fn random_choice(items: Vec<String>) -> IpeTask<String> {
    ipe_runtime::random::random_choice(items)
}

// ── File kernels ───────────────────────────────────────────────────────────
pub fn file_read_file(path: ipe_runtime::path::Path) -> IpeTask<String> {
    ipe_runtime::file::file_read_file(path)
}

pub fn file_write_file(path: ipe_runtime::path::Path, content: String) -> IpeTask<()> {
    ipe_runtime::file::file_write_file(path, content)
}

pub fn file_delete(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_delete(path)
}

// ── Task combinators ───────────────────────────────────────────────────────
pub fn task_fail<A: Send + 'static>(e: IpeError) -> IpeTask<A> {
    ipe_runtime::task::task_fail(e)
}

pub fn task_map<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> B + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<B> {
    ipe_runtime::task::task_map(f, t)
}

pub fn task_and_then<A: Send + 'static, B: Send + 'static>(
    t: IpeTask<A>,
    f: Box<dyn FnOnce(A) -> IpeTask<B> + Send + 'static>,
) -> IpeTask<B> {
    ipe_runtime::task::task_and_then(t, f)
}

pub fn task_map_error<A: Send + 'static>(
    f: Box<dyn Fn(IpeError) -> IpeError + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<A> {
    ipe_runtime::task::task_map_error(f, t)
}

pub fn task_on_error<A: Send + 'static>(
    f: Box<dyn FnOnce(IpeError) -> IpeTask<A> + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<A> {
    ipe_runtime::task::task_on_error(f, t)
}

pub fn task_from_result<A: Send + 'static>(r: IpeResult<IpeError, A>) -> IpeTask<A> {
    ipe_runtime::task::task_from_result(r)
}

pub fn task_and_then_result<A: Send + 'static, B: Send + 'static>(
    f: Box<dyn Fn(A) -> IpeResult<IpeError, B> + Send + 'static>,
    t: IpeTask<A>,
) -> IpeTask<B> {
    ipe_runtime::task::task_and_then_result(f, t)
}

pub fn task_sequence<A: Send + 'static>(tasks: Vec<IpeTask<A>>) -> IpeTask<Vec<A>> {
    ipe_runtime::task::task_sequence(tasks)
}

pub fn task_parallel<A: Send + 'static>(tasks: Vec<IpeTask<A>>) -> IpeTask<Vec<A>> {
    ipe_runtime::task::task_parallel(tasks)
}

pub fn task_run<A: Send + 'static>(t: IpeTask<A>) -> IpeResult<IpeError, A> {
    ipe_runtime::task::task_run(t)
}

// ── Io kernels ─────────────────────────────────────────────────────────────
pub fn io_read_line(_: ()) -> IpeTask<String> {
    ipe_runtime::io::io_read_line(())
}

pub fn io_write_stdout(s: String) -> IpeTask<()> {
    ipe_runtime::io::io_write_stdout(s)
}

pub fn io_write_stderr(s: String) -> IpeTask<()> {
    ipe_runtime::io::io_write_stderr(s)
}

pub fn io_println(msg: String) -> IpeTask<()> {
    ipe_runtime::io::io_println(msg)
}

pub fn io_eprintln(msg: String) -> IpeTask<()> {
    ipe_runtime::io::io_eprintln(msg)
}

// ── System kernels ─────────────────────────────────────────────────────────
pub fn system_getenv(key: String) -> IpeTask<String> {
    ipe_runtime::system::system_getenv(key)
}

pub fn system_getenv_or(key: String, default: String) -> String {
    ipe_runtime::system::system_getenv_or(key, default)
}

pub fn system_get_arg(n: i64) -> IpeTask<IpeMaybe<String>> {
    ipe_runtime::system::system_get_arg(n)
}

pub fn system_getenv_int(key: String) -> IpeTask<i64> {
    ipe_runtime::system::system_getenv_int(key)
}

pub fn system_getenv_bool(key: String) -> IpeTask<bool> {
    ipe_runtime::system::system_getenv_bool(key)
}

pub fn system_cwd(_: ()) -> IpeTask<String> {
    ipe_runtime::system::system_cwd(())
}

pub fn system_getcwd(_: ()) -> IpeTask<String> {
    ipe_runtime::system::system_getcwd(())
}

pub fn system_load_env(_: ()) -> IpeTask<()> {
    ipe_runtime::system::system_load_env(())
}

pub fn system_exit(code: i64) -> ! {
    ipe_runtime::system::system_exit(code)
}

// ── File kernels ───────────────────────────────────────────────────────────
pub fn file_exists(path: ipe_runtime::path::Path) -> IpeTask<bool> {
    ipe_runtime::file::file_exists(path)
}

pub fn file_remove(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_remove(path)
}

pub fn file_mkdir_all(path: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_mkdir_all(path)
}

pub fn file_read_file_limit(path: ipe_runtime::path::Path, limit: i64) -> IpeTask<String> {
    ipe_runtime::file::file_read_file_limit(path, limit)
}

pub fn file_read_file_bytes(path: ipe_runtime::path::Path) -> IpeTask<Vec<i64>> {
    ipe_runtime::file::file_read_file_bytes(path)
}

pub fn file_append(path: ipe_runtime::path::Path, content: String) -> IpeTask<()> {
    ipe_runtime::file::file_append(path, content)
}

pub fn file_read_dir(path: ipe_runtime::path::Path) -> IpeTask<Vec<String>> {
    ipe_runtime::file::file_read_dir(path)
}

pub fn file_is_dir(path: ipe_runtime::path::Path) -> IpeTask<bool> {
    ipe_runtime::file::file_is_dir(path)
}

pub fn file_temp_file(prefix: String) -> IpeTask<String> {
    ipe_runtime::file::file_temp_file(prefix)
}

pub fn file_temp_dir(prefix: String) -> IpeTask<String> {
    ipe_runtime::file::file_temp_dir(prefix)
}

pub fn file_copy(src: ipe_runtime::path::Path, dst: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_copy(src, dst)
}

pub fn file_rename(src: ipe_runtime::path::Path, dst: ipe_runtime::path::Path) -> IpeTask<()> {
    ipe_runtime::file::file_rename(src, dst)
}

pub fn main_describe(ts: Vec<IpeTask<String>>) -> String {
    let _ipe_recursion_guard = crate::recursion_guard();
    match ipe_runtime::list::ipe_list_view_owned::<_, 2>(ts) {
        ([None, ..], _) => "none".to_string(),
        ([Some(_), None, ..], _) => "one".to_string(),
        (__ipe_v0_a, __ipe_v0_t) => {
            let other = ipe_runtime::list::ipe_list_view_rest(__ipe_v0_a, __ipe_v0_t);
            format!(
                "{}{}",
                "count ".to_string(),
                string_from_int(list_length(other))
            )
        }
    }
}

pub fn main_sequence(ts: Vec<IpeTask<String>>) -> IpeTask<String> {
    let _ipe_recursion_guard = crate::recursion_guard();
    match ipe_runtime::list::ipe_list_view_owned::<_, 2>(ts) {
        ([None, ..], _) => task_succeed("".to_string()),
        ([Some(t), None, ..], _) => t,
        ([Some(t), __ipe_v0_s1], __ipe_v0_t) => {
            let rest = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s1], __ipe_v0_t);
            task_map2(
                {
                    let __ipe_fn: Box<dyn Fn(String, String) -> String + Send + Sync + 'static> =
                        Box::new(move |a: String, b: String| -> String { format!("{}{}", a, b) });
                    __ipe_fn
                },
                t,
                crate::main_sequence(rest),
            )
        }
    }
}

pub fn main_first_two(ts: Vec<IpeTask<String>>) -> IpeTask<String> {
    let _ipe_recursion_guard = crate::recursion_guard();
    match ipe_runtime::list::ipe_list_view_owned::<_, 3>(ts) {
        ([Some(x), Some(y), __ipe_v0_s2], __ipe_v0_t) => {
            let rest = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s2], __ipe_v0_t);
            ({
                let n = list_length(rest);
                task_map2(
                    {
                        let __ipe_fn: Box<
                            dyn Fn(String, String) -> String + Send + Sync + 'static,
                        > = Box::new(move |a: String, b: String| -> String {
                            format!("{}{}", a, format!("{}{}", b, string_from_int(n)))
                        });
                        __ipe_fn
                    },
                    x,
                    y,
                )
            })
        }
        _ => task_succeed("short".to_string()),
    }
}

pub fn main_pick(ts: Vec<IpeTask<String>>, n: i64) -> IpeTask<String> {
    let _ipe_recursion_guard = crate::recursion_guard();
    let mut ts = ts;
    let mut n = n;
    loop {
        match (ipe_runtime::list::ipe_list_view_owned::<_, 2>(ts), n) {
            (([Some(t), ..], _), 0) => {
                return t;
            }
            (([Some(_), __ipe_v0_s1], __ipe_v0_t), _) => {
                let r = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s1], __ipe_v0_t);
                let __tco_0 = r;
                let __tco_1 = ipe_runtime::math::ipe_int_sub(n, 1i64);
                ts = __tco_0;
                n = __tco_1;
                continue;
            }
            (([None, ..], _), _) => {
                return task_succeed("none".to_string());
            }
        }
    }
}

pub fn main_gated(ts: Vec<IpeTask<String>>, flag: String) -> IpeTask<String> {
    let _ipe_recursion_guard = crate::recursion_guard();
    match (ipe_runtime::list::ipe_list_view_owned::<_, 2>(ts), (flag).as_str()) {
        (([Some(t), ..], _), "go") => t,
        (([Some(_), __ipe_v0_s1], __ipe_v0_t), _) => {
            let r = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s1], __ipe_v0_t);
            crate::main_sequence(r)
        }
        (([None, ..], _), _) => task_succeed("empty".to_string()),
    }
}

pub fn main_first_just(ms: Vec<IpeMaybe<IpeTask<String>>>) -> IpeTask<String> {
    let _ipe_recursion_guard = crate::recursion_guard();
    let mut ms = ms;
    loop {
        match ipe_runtime::list::ipe_list_view_owned::<_, 2>(ms) {
            ([Some(IpeMaybe::Just(t)), ..], _) => {
                return t;
            }
            ([Some(IpeMaybe::Nothing), __ipe_v0_s1], __ipe_v0_t) => {
                let r = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s1], __ipe_v0_t);
                let __tco_0 = r;
                ms = __tco_0;
                continue;
            }
            ([None, ..], _) => {
                return task_succeed("no task".to_string());
            }
        }
    }
}

pub fn main_weight(m: IpeMaybe<IpeTask<String>>) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    match m {
        IpeMaybe::Just(_) => 1i64,
        IpeMaybe::Nothing => 0i64,
    }
}

pub fn main_count_justs(ms: Vec<IpeMaybe<IpeTask<String>>>) -> i64 {
    let _ipe_recursion_guard = crate::recursion_guard();
    match ipe_runtime::list::ipe_list_view_owned::<_, 2>(ms) {
        ([Some(m @ IpeMaybe::Just(_)), __ipe_v0_s1], __ipe_v0_t) => {
            let r = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s1], __ipe_v0_t);
            ipe_runtime::math::ipe_int_add(crate::main_weight(m), crate::main_count_justs(r))
        }
        ([Some(IpeMaybe::Nothing), __ipe_v0_s1], __ipe_v0_t) => {
            let r = ipe_runtime::list::ipe_list_view_rest([__ipe_v0_s1], __ipe_v0_t);
            crate::main_count_justs(r)
        }
        ([None, ..], _) => 0i64,
    }
}

pub fn main_size_then_run(ts: Vec<IpeTask<String>>) -> IpeTask<String> {
    let _ipe_recursion_guard = crate::recursion_guard();
    ({
        let size = match (ts).as_slice() {
            [] => "empty ".to_string(),
            [_] => "one ".to_string(),
            _ => "many ".to_string(),
        };
        ({
            let eta_0: IpeTask<String> = crate::main_sequence(ts);
            task_and_then(
                eta_0,
                ({
                    let size = size.clone();
                    {
                        let __ipe_fn: Box<
                            dyn Fn(String) -> IpeTask<String> + Send + Sync + 'static,
                        > = Box::new(move |s: String| -> IpeTask<String> {
                            task_succeed(format!("{}{}", size.clone(), s))
                        });
                        __ipe_fn
                    }
                }),
            )
        })
    })
}

pub fn main_say(t: IpeTask<String>) -> IpeTask<()> {
    let _ipe_recursion_guard = crate::recursion_guard();
    ({
        let eta_0: IpeTask<String> = t;
        task_and_then(
            eta_0,
            Box::new(move |s: String| -> IpeTask<()> { io_println(s) }),
        )
    })
}

pub fn ipe_main() -> IpeTask<()> {
    let _ipe_recursion_guard = crate::recursion_guard();
    ({
        let eta_12: IpeTask<()> = ({
            let eta_11: IpeTask<()> = ({
                let eta_10: IpeTask<()> = ({
                    let eta_9: IpeTask<()> = ({
                        let eta_8: IpeTask<()> = ({
                            let eta_7: IpeTask<()> = ({
                                let eta_6: IpeTask<()> = ({
                                    let eta_5: IpeTask<()> = ({
                                        let eta_4: IpeTask<()> = ({
                                            let eta_3: IpeTask<()> = ({
                                                let eta_2: IpeTask<()> = ({
                                                    let eta_1: IpeTask<()> = ({
                                                        let eta_0: IpeTask<()> =
                                                            crate::main_say(
                                                                crate::main_sequence(
                                                                    vec![
                                                                        task_succeed(
                                                                            "a".to_string(),
                                                                        ),
                                                                        task_succeed(
                                                                            "b".to_string(),
                                                                        ),
                                                                        task_succeed(
                                                                            "c".to_string(),
                                                                        ),
                                                                    ],
                                                                ),
                                                            );
                                                        task_and_then(
                                                            eta_0,
                                                            Box::new(move |arg_0: ()| -> IpeTask<()> {
                                                                io_println(
                                                                    crate::main_describe(
                                                                        Vec::<IpeTask<String>>::new(),
                                                                    ),
                                                                )
                                                            }),
                                                        )
                                                    });
                                                    task_and_then(
                                                        eta_1,
                                                        Box::new(move |arg_1: ()| -> IpeTask<()> {
                                                            io_println(
                                                                crate::main_describe(
                                                                    vec![
                                                                        task_succeed(
                                                                            "x".to_string(),
                                                                        ),
                                                                    ],
                                                                ),
                                                            )
                                                        }),
                                                    )
                                                });
                                                task_and_then(
                                                    eta_2,
                                                    Box::new(move |arg_2: ()| -> IpeTask<()> {
                                                        io_println(crate::main_describe(vec![
                                                            task_succeed("x".to_string()),
                                                            task_succeed("y".to_string()),
                                                            task_succeed("z".to_string()),
                                                        ]))
                                                    }),
                                                )
                                            });
                                            task_and_then(
                                                eta_3,
                                                Box::new(move |arg_3: ()| -> IpeTask<()> {
                                                    crate::main_say(
                                                        crate::main_first_two(
                                                            vec![
                                                                task_succeed("p".to_string()),
                                                                task_succeed("q".to_string()),
                                                                task_succeed("r".to_string()),
                                                            ],
                                                        ),
                                                    )
                                                }),
                                            )
                                        });
                                        task_and_then(
                                            eta_4,
                                            Box::new(move |arg_4: ()| -> IpeTask<()> {
                                                crate::main_say(
                                                    crate::main_first_two(
                                                        vec![task_succeed("p".to_string())],
                                                    ),
                                                )
                                            }),
                                        )
                                    });
                                    task_and_then(
                                        eta_5,
                                        Box::new(move |arg_5: ()| -> IpeTask<()> {
                                            crate::main_say(crate::main_pick(
                                                vec![
                                                    task_succeed("a".to_string()),
                                                    task_succeed("b".to_string()),
                                                    task_succeed("c".to_string()),
                                                ],
                                                1i64,
                                            ))
                                        }),
                                    )
                                });
                                task_and_then(
                                    eta_6,
                                    Box::new(move |arg_6: ()| -> IpeTask<()> {
                                        crate::main_say(
                                            crate::main_pick(
                                                vec![task_succeed("a".to_string())],
                                                5i64,
                                            ),
                                        )
                                    }),
                                )
                            });
                            task_and_then(
                                eta_7,
                                Box::new(move |arg_7: ()| -> IpeTask<()> {
                                    crate::main_say(crate::main_gated(
                                        vec![
                                            task_succeed("x".to_string()),
                                            task_succeed("y".to_string()),
                                        ],
                                        "go".to_string(),
                                    ))
                                }),
                            )
                        });
                        task_and_then(
                            eta_8,
                            Box::new(move |arg_8: ()| -> IpeTask<()> {
                                crate::main_say(crate::main_gated(
                                    vec![
                                        task_succeed("x".to_string()),
                                        task_succeed("y".to_string()),
                                    ],
                                    "stop".to_string(),
                                ))
                            }),
                        )
                    });
                    task_and_then(
                        eta_9,
                        Box::new(move |arg_9: ()| -> IpeTask<()> {
                            crate::main_say(crate::main_first_just(vec![
                                IpeMaybe::Nothing,
                                IpeMaybe::Just(task_succeed("j".to_string())),
                                IpeMaybe::Just(task_succeed("k".to_string())),
                            ]))
                        }),
                    )
                });
                task_and_then(
                    eta_10,
                    Box::new(move |arg_10: ()| -> IpeTask<()> {
                        crate::main_say(crate::main_first_just(vec![IpeMaybe::Nothing]))
                    }),
                )
            });
            task_and_then(
                eta_11,
                Box::new(move |arg_11: ()| -> IpeTask<()> {
                    io_println(string_from_int(crate::main_count_justs(vec![
                        IpeMaybe::Just(task_succeed("a".to_string())),
                        IpeMaybe::Nothing,
                        IpeMaybe::Just(task_succeed("b".to_string())),
                    ])))
                }),
            )
        });
        task_and_then(
            eta_12,
            Box::new(move |arg_12: ()| -> IpeTask<()> {
                crate::main_say(crate::main_size_then_run(vec![
                    task_succeed("a".to_string()),
                    task_succeed("b".to_string()),
                ]))
            }),
        )
    })
}

// List helpers
pub fn list_map_consume<T0, T1>(f: impl Fn(T0) -> T1, list: Vec<T0>) -> Vec<T1> {
    list.into_iter().map(f).collect()
}

// ===========================================
// ENTRY POINT
// ===========================================

fn main() {
    // Synchronous-panic gate (parity: rt.LogPanicAndExit) —
    // classify an escaping panic (div-by-zero / index-OOB /
    // overflow) into a Ipe error + exit 1, not a raw Rust backtrace.
    ipe_runtime::core::install_panic_classifier();
    match block_on(ipe_main()) {
        IpeResult::Ok(_) => (),
        IpeResult::Err(e) => {
            ipe_runtime::core::eprint_task_error(&e.to_string());
            std::process::exit(1);
        }
    }
}
